# Generated by Django 4.0.1 on 2022-01-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='account_name', max_length=255),
        ),
    ]
