# Generated by Django 4.0.1 on 2022-02-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
