# Generated by Django 4.0.1 on 2022-02-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_transactiontype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='update_date',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='update_date',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
